config/routes.rb
TwitterClone::Application.routes.draw do
  root to: 'users#index'

  resources :sessions
  resources :users
  resources :tweets
  resources :relationships

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  after_create :send_followed_notification


private
  def send_followed_notification
    UserMailer.followed_notification(self.followed_id, self.follower_id).deliver
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :user_id, presence: true
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :email, presence: true
  has_many :tweets
  has_many :followed_users, through: :relationships, source: :followed
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  before_create { generate_token(:auth_token) }
  after_create :send_signup_confirmation

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

private

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_signup_confirmation
    UserMailer.signup_confirmation(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized." if current_user.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user]
      @user.update(users_params)
    end
      redirect_to user_path
  end

  def create
    @relationship = Relationship.new(relationships_params)
    if @relationship.save
      redirect_to user_path(@relationship.followed_id)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(root_path)
  end

private

  def relationships_params
    params.require(:relationship).permit(:followed_id, :follower_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
    user = User.new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:alert] = "Email or password is invalid"
      redirect_to :back
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if params[:tweet]
      @tweet.update(tweets_params)
    end
    redirect_to tweet_path
  end

  def create
    @tweet = Tweet.new(tweets_params)
    if @tweet.save
      flash[:notice] = "tweet created!"
      respond_to do |format|
        format.html { redirect_to user_path(@tweet.user) }
        format.js
      end
    else
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to(root_path)
  end

private

  def tweets_params
    params.require(:tweet).permit(:user_id, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
    @users = User.all
  end

  def show
    @tweet = Tweet.new
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user]
      @user.update(users_params)
    end
      redirect_to user_path
  end

  def create
    @user = User.new(users_params)
    if @user.save
      cookies[:auth_token] = @user.auth_token
      flash[:notice] = "User created!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(root_path)
  end

private

  def users_params
    params.require(:user).permit(:username, :password, :password_confirmation, :auth_token, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Please correct errors:</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title)+" | Twitter Clone" : "Twitter Clone" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="navbar navbar-default navbar-fixed-top">
    <%= link_to "Home", root_url, class: "navbar-text pull-left" %>
    <div class="navbar-text">
      <div class="center-bold">
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      </div>
    </div>
    <% if current_user %>
      <%= link_to "Log Out", session_path("current"), method: "delete", class: "navbar-text pull-right" %>
      <div class="navbar-text pull-right">
       Logged in as &nbsp;<%= link_to current_user.username, user_path(current_user) %>
      </div>
    <% else %>
      <%= link_to "Log In", new_session_path, class: "navbar-text pull-right" %>
      <%= link_to "Sign Up", new_user_path, class: "navbar-text pull-right" %>
    <% end %>
  </div>

  <div id="main">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/tweets/create.js.erb
$('#tweets').prepend('<div class="row"><span class="tweetcontent"><%= @tweet.content %></span><br/><span class="tweetdatetime"><%= @tweet.created_at.strftime("%l:%M %p, %D") %></span></div>');

app/views/users/_form.html.erb
<%= render 'layouts/errors', object: @user %>


<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.text_field :username, placeholder: "Username" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, placeholder: "Email address..." %>
  </div>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<%= content_for :title, "Users" %>

<h1>Users</h1>

<% @users.each do |user| %>
  <li><%= link_to user.username, user_path(user) %></li>
<% end %>

app/views/users/new.html.erb
<%= content_for :title, "New User" %>

<h1>Register</h1>


<%= render 'form' %>

app/views/users/show.html.erb
<%= content_for :title, @user.username %>

<h1>Tweets by <%= @user.username %>
                <% if current_user != @user %>
                  <%= form_for @relationship, url: relationships_path, method: "post" do |f| %>
                    <%= f.hidden_field :followed_id, value: @user.id %>
                    <%= f.hidden_field :follower_id, value: current_user.id %>
                    <%= f.submit "Follow", class: "btn btn-info" %>
                  <% end %>
                <% end %>
              </h1>

<% if current_user == @user %>
  <%= form_for @tweet, url: tweets_path, method: "post", remote: true do |f| %>
    <%= f.submit "Tweet", class: "btn btn-primary" %>
    <%= f.text_field :content, placeholder: "Tweet something!", class: "big-rounded-corners" %>
    <%= f.hidden_field :user_id, value: @user.id %>
  <% end %>
<% end %>

<div class="col-md-3">
  <h4>Followers</h4>
  <% @user.followers.each do |follower| %>
    <%= follower.username %>
  <% end %>
  <br/>
  <h4>Following</h4>
  <% @user.followed_users.each do |followed| %>
    <%= followed.username %>
  <% end %>

</div>

<div id="tweets" class="col-md-6">
  <% @user.tweets.order(created_at: :desc).each do |tweet| %>
    <div class="row">
      <span class="tweetcontent"><%= tweet.content %></span><br/>
      <span class="tweetdatetime"><%= tweet.created_at.strftime("%l:%M %p, %D") %></span>
    </div>
  <% end %>
</div>